version: "2"

services:
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - "55432:5432"
    environment:
      - POSTGRES_USER:postgres
      - POSTGRES_PASSWORD:postgres
      - POSTGRES_DB:starter
    volumes:
      - "pgdata:/var/lib/postgresql/data/"

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - "redisdata:/data"

volumes: 
  pgdata:
  redisdata: